routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'MainController@index')->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'Backend'], function () {
  Route::group(['middleware' => ['role:Administrator']], function () {
		Route::get('/', 'Backend\MainController@index')->name('admin.index');

		Route::resource('Users', 'Backend\UserController');
		Route::put('Users/{id}/Restore', 'Backend\UserController@restore')->name('Users.restore');
		Route::delete('Users/{id}/Permanent', 'Backend\UserController@permanentDelete')->name('Users.perma');
		
		Route::resource('Type', 'Backend\TypeController')->except(['create', 'show']);
		Route::put('Type/{id}/Restore', 'Backend\TypeController@restore')->name('Type.restore');
		Route::delete('Type/{id}/Permanent', 'Backend\TypeController@permanentDelete')->name('Type.perma');
		
		Route::resource('Currency', 'Backend\CurrencyController')->except(['create', 'show']);
		Route::put('Currency/{id}/Restore', 'Backend\CurrencyController@restore')->name('Currency.restore');
		Route::delete('Currency/{id}/Permanent', 'Backend\CurrencyController@permanentDelete')->name('Currency.perma');
		
		Route::resource('Package', 'Backend\PackageController');
		Route::put('Package/{id}/Restore', 'Backend\PackageController@restore')->name('Package.restore');
		Route::delete('Package/{id}/Permanent', 'Backend\PackageController@permanentDelete')->name('Package.perma');

		Route::resource('Itinerary', 'Backend\ItineraryController')->except(['index', 'create']);
		Route::get('/Itinerary/{id}/create', 'Backend\ItineraryController@index')->name('Itinerary.index');

	});
});

app/Http/Controllers/Backend/CurrencyController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Currency;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CurrencyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
				$currency = Currency::orderBy('created_at', 'DESC')->paginate(10);
				$tcurrency = Currency::orderBy('deleted_at')->onlyTrashed()->get();
				return view('backend.currency.index', compact('currency', 'tcurrency'));
		}

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
					'code' => 'required|string|unique:currencies,code',
					'name' => 'required|string',
					'description' => 'nullable|string'
				]);

				try {
					$currency = Currency::firstOrCreate([
						'code' => $request->code,
						'name' => $request->name,
						'description' => $request->description,
					]);

					session()->flash('success', 'Data Mata Uang di-Tambahkan !');
					return redirect(route('Currency.index'));
				} catch (\Exception $e) {
					abort(404);
					session()->flash('error', 'Terjadi Kesalahan !');
					return redirect()->back();
				}
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
			try {
				$edit = Currency::findOrFail($id);
				$currency = Currency::orderBy('created_at', 'DESC')->paginate(10);
				$tcurrency = Currency::orderBy('deleted_at')->onlyTrashed()->get();
				return view('backend.currency.index', compact('currency', 'tcurrency', 'edit'));
			} catch (\Exception $e) {
				abort(404);
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back();
			}
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
				'code' => 'required|string|unique:currencies,code,'.$id,
				'name' => 'required|string',
				'description' => 'nullable|string', 
			]);

			try {
				$currency = Currency::findOrFail($id);
				$currency->update([
					'code' => $request->code,
					'name' => $request->name,
					'description' => $request->description
				]);

				session()->flash('info', 'Data Mata Uang di-Ubah !');
				return redirect(route('Currency.index'));
			} catch (\Exception $e) {
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back();
			}
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      try {
				$currency = Currency::findOrFail($id);
				$currency->delete();
				session()->flash('warning', 'Data Mata Uang di-Hapus !');
				return redirect(route('Currency.index'));
			} catch (\Exception $e) {
				abort(404);
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back();
			}
		}
		
		public function restore(Request $request, $id)
		{
			try {
				$currency = Currency::onlyTrashed()->where('id', '=', $id)->firstOrFail();
				$currency->restore();
				session()->flash('success', 'Jenis Tur di-Pulihkan !');
				return redirect(route('Currency.index'));
			} catch (\Exception $e) {
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back();
			}
		}

		public function permanentDelete(Request $request, $id)
		{
			try {
				$currency = Currency::onlyTrashed()->where('id', '=', $id)->firstOrFail();
				$currency->forceDelete();
				session()->flash('warning', 'Data Jenis Tur di-Hapus Permanen !');
				return redirect(route('Currency.index'));
			} catch (\Exception $e) {
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back();
			}
		}
}

app/Http/Controllers/Backend/ItineraryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Itinerary;
use App\Package;
use Illuminate\Http\Request;

class ItineraryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
      try {
				$package = Package::findOrFail($id);
				return view('backend.itinerary.index', compact('package', 'itinerary'));
			} catch (\Exception $e) {
				abort(404);
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back();
			}
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
				'package_id' => 'required|numeric|exists:packages,id',
				'day' => 'required|numeric',
				'name' => 'required|string',
				'transport' => 'nullable|string',
				'hotel' => 'nullable|string',
				'meals' => 'nullable|string',
				'description' => 'required|string',
			]);

			try {
				$package = Package::findOrFail($request->package_id);
				$itinerary = Itinerary::where('package_id', '=', $request->package_id)->where('day', '=' ,$request->day)->first();
				if ($itinerary != null) {
					$itinerary->update([
						'name' => $request->name,
						'transport' => $request->transport,
						'hotel' => $request->hotel,
						'meals' => $request->meals,
						'description' => $request->description
					]);

					$data = [
						'code' => 'success',
						'message' => 'Data Perjalanan di-Ubah !',
					];
					return response()->json($data, 200);
				} else {
					if ($request->day > $package->duration) {
						$data = [
							'code' => 'error',
							'message' => 'Terjadi Kesalahan, Silahkan Refresh Ulang Halaman !',
						];
						return response()->json($data, 200);
					} else {
						$itinerary = Itinerary::create([
							'package_id' => $request->package_id,
							'day' => $request->day,
							'name' => $request->name,
							'hotel' => $request->hotel,	
							'transport' => $request->transport,
							'meals' => $request->meals,
							'description' => $request->description
						]);

						$data = [
							'code' => 'success',
							'message' => 'Data Perjalanan di-Simpan !',
						];
						return response()->json($data, 200);
					}
				}
			} catch (\Exception $e) {
				$data = [
					'code' => 'error',
					'message' => 'Terjadi Kesalahan, Hubungi Operator !',
				];
				return response()->json($data);
			}
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/MainController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class MainController extends Controller
{
    public function index()
    {
        return view('backend.main');
    }
}

app/Http/Controllers/Backend/PackageController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Currency;
use App\Http\Controllers\Controller;
use App\Package;
use App\Type;
use Illuminate\Http\Request;

class PackageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
			$package = Package::orderBy('created_at', 'DESC')->paginate(10);
			$tpackage = Package::orderBy('deleted_at')->onlyTrashed()->get();
			return view('backend.package.index', compact('package', 'tpackage'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
			$type = Type::orderBy('name', 'ASC')->get();
			$currency = Currency::orderBy('code', 'ASC')->get();
      return view('backend.package.create', compact('type', 'currency'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
			$this->validate($request, [
				'name' => 'required|string',
				'type_id' => 'required|numeric|exists:types,id',
				'duration' => 'required|numeric|min:1',
				'minimum' => 'required|numeric|min:1',
				'currency_id' => 'required|numeric|exists:currencies,id',
				'expired_date' => 'required|string',
				'description' => 'required|string',
			]);

			try {
				$tgl = '';
				$tgl = explode('/', $request->expired_date);
				if (count($tgl) != '3') {
					return redirect()->back()->withInput($request->all());
					session()->flash('error', 'Format Tanggal Salah !');
				} else {
					$tgl = $tgl[2] . '-' . $tgl[1] . '-' . $tgl[0];
					$package = Package::firstOrCreate([
						'name' => $request->name,
						'type_id' => $request->type_id,
						'duration' => $request->duration,
						'minimum' => $request->minimum,
						'currency_id' => $request->currency_id,
						'expired_date' => $tgl,
						'description' => $request->description,
					]);

					session()->flash('success', 'Data Paket Tur di-Tambahkan !');

					if ($request->has('detail')) {
						return redirect(route('Package.show', $package->id));
					} else if ($request->has('again')) {
						return redirect(route('Package.create'));
					} else {
						return redirect(route('Package.index'));
					}
				}
			} catch (\Exception $e) {
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back()->withInput();
			}
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      try {
				$package = Package::findOrFail($id);
				return view('backend.package.show', compact('package'));
			} catch (\Exception $e) {
				abort(404);
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back();
			}
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
			try {
				$edit = Package::findOrFail($id);
				$type = Type::orderBy('name', 'ASC')->get();
				$currency = Currency::orderBy('code', 'ASC')->get();
				return view('backend.package.edit', compact('type', 'currency', 'edit'));
			} catch (\Exception $e) {
				abort(404);
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back();
			}
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
			$this->validate($request, [
				'name' => 'required|string',
				'type_id' => 'required|numeric|exists:types,id',
				'duration' => 'required|numeric|min:1',
				'minimum' => 'required|numeric|min:1',
				'currency_id' => 'required|numeric|exists:currencies,id',
				'expired_date' => 'required|string',
				'description' => 'required|string',
			]);

			try {
				$package = Package::findOrFail($id);
				$tgl = '';
				$tgl = explode('/', $request->expired_date);
				if (count($tgl) != '3') {
					return redirect()->back()->withInput($request->all());
					session()->flash('error', 'Format Tanggal Salah !');
				} else {
					$tgl = $tgl[2] . '-' . $tgl[1] . '-' . $tgl[0];
					$package->update([
						'name' => $request->name,
						'type_id' => $request->type_id,
						'duration' => $request->duration,
						'minimum' => $request->minimum,
						'currency_id' => $request->currency_id,
						'expired_date' => $tgl,
						'description' => $request->description,
					]);

					session()->flash('info', 'Data Paket Tur di-Ubah !');
					return redirect(route('Package.index'));
				}
			} catch (\Exception $e) {
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back();
			}
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      try {
				$package = Package::findOrFail($id);
				$package->delete();

				session()->flash('warning', 'Paket Tur di-Non Aktifkan !');
				return redirect(route('Package.index'));
			} catch (\Exception $e) {
				abort(404);
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back();
			}
		}
		
		public function restore(Request $request, $id)
		{
			try {
				$package = Package::onlyTrashed()->where('id', '=', $id)->firstOrFail();
				$package->restore();
				session()->flash('success', 'Paket Tur di-Pulihkan !');
				return redirect(route('Package.index'));
			} catch (\Exception $e) {
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back();
			}
		}

		public function permanentDelete(Request $request, $id)
		{
			try {
				$package = Package::onlyTrashed()->where('id', '=', $id)->firstOrFail();
				$package->forceDelete();
				session()->flash('warning', 'Data Paket Tur di-Hapus Permanen !');
				return redirect(route('Package.index'));
			} catch (\Exception $e) {
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back();
			}
		}
}

resources/views/backend/user/index.blade.php
@extends('backend.app')

@section('content')
<div class="row" style="margin-top: 15px;">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<div class="portlet light bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-users"></i>
					<span class="caption-subject bold"> &ensp; Data Pengguna </span>
				</div>
				<div class="actions">
					<div class="btn-group">
						<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#trashed-modal">
							<i class="fa fa-trash"></i> 
						</button>

						<a href="{{ route('Users.create') }}" class="btn blue">
							<i class="icon-pencil"></i> &ensp; Tambah Baru
						</a>
					</div>
				</div>
			</div>
			<div class="portlet-body">
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
						
					</div>
					<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
						<form action="{{ url('Backend/Users') }}" method="get" class="form-horizontal">
							<div class="form-group row">
								<label for="cari" class="col-xs-12 col-sm-2 col-md-4 col-lg-4 control-label text-left">Cari Data :</label>
								<div class="col-xs-12 col-sm-10 col-md-8 col-lg-8">
									@if (request()->has('cari'))
										<div class="input-group">
											<input type="text" name="cari" id="cari" class="form-control" placeholder="Cari Data Pengguna..." style="border-radius: 0px;" value="{{ request()->get('cari') ? request()->get('cari'):'' }}">
											<span class="input-group-addon" style="border-radius: 0px !important;">
												<a href="{{ route('Users.index') }}" style="border-radius: 0px; text-decoration: none !important;"><span class="fa fa-times"></span> Reset</a>
											</span>
										</div>
									@else  
										<input type="text" name="cari" id="cari" class="form-control" placeholder="Cari Data Pengguna..." style="border-radius: 0px;" value="{{ request()->get('cari') ? request()->get('cari'):'' }}">
									@endif
								</div>
							</div>
						</form>
					</div>
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div class="table-responsive">
							<table class="table">
								<thead>
									<tr>
										<th class="text-center">No.</th>
										<th>Nama Pengguna</th>
										<th>E-Mail</th>
										<th>Hak Akses</th>
										<th>Tanggal Buat</th>
										<th>Terakhir Login</th>
										<th class="text-center">Aksi</th>
									</tr>
								</thead>
								<tbody>
									@php
										if (request()->has('page')) {
											$no = request()->get('page') * 10 - 10 + 1;
										} else {
											$no = 1;
										}
									@endphp
									@forelse ($user as $item)
										<tr>
											<td class="text-center" style="font-weight: 600; padding-top: 12px;">{{ $no++ }}.</td>
											<td style="padding-top: 12px;">{{ $item->first_name }} {{ $item->last_name }}</td>
											<td style="padding-top: 12px;">{{ $item->email }}</td>
											<td style="padding-top: 12px;">{{ $item->roles->first()->name }}</td>
											<td style="padding-top: 12px;">{{ date('d/m/Y H:i:s', strtotime($item->created_at)) }}</td>
											<td style="padding-top: 12px;">{{ date('d/m/Y H:i:s', strtotime($item->last_login_at)) }}</td>
											<td class="text-center" style="min-width: 150px !important;">
												<div class="btn-group">
													<a href="{{ route('Users.show', $item->id) }}" class="btn btn-sm btn-info flat">
														<i class="fa fa-arrow-right"></i>
													</a>
													<a href="{{ route('Users.edit', $item->id) }}" class="btn btn-sm btn-warning flat">
														<i class="fa fa-edit"></i>
													</a>
													<a href="javascript:void(0)" class="btn btn-sm btn-danger" onclick="event.preventDefault(); document.getElementById('destroy'+{{ $item->id }}).submit();">
														<i class="fa fa-trash"></i>
													</a>
													<form action="{{ route('Users.destroy', $item->id) }}" method="post" id="destroy{{ $item->id }}">
														@csrf
														@method('DELETE')
													</form>
												</div>
											</td>
										</tr>
									@empty
										<tr>
											<td colspan="6" class="text-center">Belum Ada Data Pengguna.</td>
										</tr>
									@endforelse
								</tbody>
								<tfoot>
									<tr>
										<td colspan="6" class="text-right">
											{{ $user->links() }}
										</td>
									</tr>
								</tfoot>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="trashed-modal">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Tempat Sampah Data Pengguna</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="table-responsive" style="max-height: 500px;">
					<table class="table table-stripped">
						<thead>
							<tr>
								<th class="text-center">No.</th>
								<th>Nama Pengguna</th>
								<th>E-Mail</th>
								<th>Hak Akses</th>
								<th>Tanggal Hapus</th>
								<th class="text-center">Aksi</th>
							</tr>
						</thead>
						<tbody>
							@forelse ($tuser as $item)
								<tr>
									<td class="text-center" style="font-weight: 600; padding-top: 12px;">{{ $loop->iteration }}.</td>
									<td style="padding-top: 12px;">{{ $item->first_name }} {{ $item->last_name }}</td>
									<td style="padding-top: 12px;">{{ $item->email }}</td>
									<td style="padding-top: 12px;">{{ $item->roles->first()->name }}</td>
									<td style="padding-top: 12px;">{{ date('d/m/Y H:i:s', strtotime($item->deleted_at)) }}</td>
									<td class="text-center" style="min-width: 150px !important;">
										<div class="btn-group">
											<a href="javascript:void(0)" class="btn btn-sm btn-success" onclick="event.preventDefault(); document.getElementById('restore'+{{ $item->id }}).submit();">
												<i class="fa fa-undo"></i> Pulihkan
											</a>
											<a href="javascript:void(0)" class="btn btn-sm btn-danger" onclick="event.preventDefault(); document.getElementById('perma'+{{ $item->id }}).submit();">
												<i class="fa fa-trash"></i> Hapus
											</a>
											
											<form action="{{ route('Users.restore', $item->id) }}" method="post" id="restore{{ $item->id }}">
													@csrf
													@method('PUT')
												</form>
											<form action="{{ route('Users.perma', $item->id) }}" method="post" id="perma{{ $item->id }}">
												@csrf
												@method('DELETE')
											</form>
										</div>
									</td>
								</tr>
							@empty
								
							@endforelse
						</tbody>
					</table>
				</div>
			</div>
			<div class="modal-footer justify-content-between">
				<button type="button" class="btn btn-outline-light" data-dismiss="modal">Tutup</button>
			</div>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>

@endsection

resources/views/backend/user/show.blade.php
@extends('backend.app')

@section('content')
	<div class="row" style="margin-top: 15px;">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="portlet light bordered">
				<div class="portlet-title">
					<div class="caption">
						<i class="fa fa-user"></i>
						<span class="caption-subject bold"> &ensp; Detail Pengguna</span>
					</div>
					<div class="actions">
						<div class="btn-group">
							<a href="{{ route('Users.edit', $user->id) }}" class="btn btn-sm btn-warning">
								<i class="fa fa-pencil"></i> &ensp; Edit Data Pengguna
							</a>
							<a href="{{ route('Users.index') }}" class="btn red">
								<i class="fa fa-times"></i> &ensp; Kembali
							</a>
						</div>
					</div>
				</div>
				<div class="portlet-body">
					<div class="hidden-xs hidden-sm" >
						<div class="row">
							<div class="col-md-3 col-lg-3 text-center">
								<img src="{{ asset('images/users') }}/{{ $user->photo }}" alt="{{ $user->first_name }}-{{ $user->photo }}" class="img-responsive center-block" style="max-height: 200px !important;">
								<h5>
									{{ $user->first_name }}
									{{ $user->last_name }}
								</h5>
								<h5>
									- {{ $user->roles->first()->name }}  -
								</h5>
								<hr style="margin: 0px; padding:0px;">
								<h5>Terakhir Login</h5>
								<h5>{{ date('H:i:s d/m/Y', strtotime($user->last_login_at)) }}</h5>
								<h5>IP : {{ $user->last_login_ip }}</h5>
							</div>
							<div class="col-md-9 col-lg-9">
								<div class="panel panel-primary" style="border-radius: 0px;">
									<div class="panel-heading clearfix" style="border-radius: 0px;">
										{{-- <div class="btn-group pull-right">
											<a href="#" data-toggle="collapse" data-target="#data-body" style="color: white; font-wight: 800;">
												<i class="fa fa-angle-down"></i>
											</a>
										</div> --}}
										<h4 class="panel-title">Data Diri Pengguna</h4>
									</div>
									<div class="panel-body">
										<div class="row">
											<div class="col-md-3 col-lg-3">
												Nama Depan
											</div>
											<div class="col-md-1 col-lg-1">:</div>
											<div class="col-md-8 col-lg-8">
												{{ $user->first_name }}
											</div>
											<div class="col-md-3 col-lg-3" style="margin-top: 4px;">
												Nama Belakang
											</div>
											<div class="col-md-1 col-lg-1" style="margin-top: 4px;">:</div>
											<div class="col-md-8 col-lg-8" style="margin-top: 4px;">
												{{ $user->last_name }}
											</div>
											<div class="col-md-3 col-lg-3" style="margin-top: 4px;">
												E-Mail
											</div>
											<div class="col-md-1 col-lg-1" style="margin-top: 4px;">:</div>
											<div class="col-md-8 col-lg-8" style="margin-top: 4px;">
												{{ $user->email }}
											</div>
											<div class="col-md-3 col-lg-3" style="margin-top: 4px;">
												Negara
											</div>
											<div class="col-md-1 col-lg-1" style="margin-top: 4px;">:</div>
											<div class="col-md-8 col-lg-8" style="margin-top: 4px;">
												{{ $user->country->name }}
											</div>
											<div class="col-md-3 col-lg-3" style="margin-top: 4px;">
												Jenis Kelamin
											</div>
											<div class="col-md-1 col-lg-1" style="margin-top: 4px;">:</div>
											<div class="col-md-8 col-lg-8" style="margin-top: 4px;">
												{{ $user->jenis_kelamin($user->gender) }}
											</div>
											<div class="col-md-3 col-lg-3" style="margin-top: 4px;">
												Tanggal Lahir
											</div>
											<div class="col-md-1 col-lg-1" style="margin-top: 4px;">:</div>
											<div class="col-md-8 col-lg-8" style="margin-top: 4px;">
												{{ date('d/m/Y', strtotime($user->date_of_birth)) }}
											</div>
											<div class="col-md-3 col-lg-3" style="margin-top: 4px;">
												Nomor Telfon
											</div>
											<div class="col-md-1 col-lg-1" style="margin-top: 4px;">:</div>
											<div class="col-md-8 col-lg-8" style="margin-top: 4px;">
												(+62) {{ $user->phone }}
											</div>
											<div class="col-md-3 col-lg-3" style="margin-top: 4px;">
												Alamat
											</div>
											<div class="col-md-1 col-lg-1" style="margin-top: 4px;">:</div>
											<div class="col-md-8 col-lg-8" style="margin-top: 4px;">
												{{ $user->address }}
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="hidden-md-hidden-lg">
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 hidden-md hidden-lg">
								XS & SM
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('script')
	<script>
		$(document).ready(function() {
			//
		});
	</script>
@endsection